# Generated by Django 5.0.6 on 2024-06-07 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('religion', models.CharField(max_length=50)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('house_street', models.CharField(max_length=50)),
                ('suburb', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=20)),
                ('post_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=50)),
                ('med_background', models.CharField(max_length=250)),
                ('contact_first_name', models.CharField(max_length=50)),
                ('contact_last_name', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=50)),
                ('contact_rel', models.CharField(max_length=20)),
                ('res_photo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
