# Generated by Django 5.0.6 on 2024-06-07 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_record_res_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='res_photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/res_photo/'),
        ),
    ]
