# Generated by Django 5.0.6 on 2024-06-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_record_res_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='res_photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/my_app/static/res_photo/'),
        ),
    ]
