# Generated by Django 5.0.6 on 2024-06-13 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_remove_record_birthday_record_res_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='contact_first_name',
            new_name='contact_first',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='contact_last_name',
            new_name='contact_last',
        ),
        migrations.RemoveField(
            model_name='record',
            name='res_photo',
        ),
    ]
