# Generated by Django 5.0.6 on 2024-06-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_rename_contact_first_name_record_contact_first_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='res_photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/my_app/static/res_photo/'),
        ),
    ]
