# Generated by Django 5.0.6 on 2024-06-21 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_activities_healthmonitoring_housekeeping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='date_time',
            field=models.DateTimeField(null=True, verbose_name='Date/Time'),
        ),
        migrations.AddField(
            model_name='activities',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.record'),
        ),
        migrations.AddField(
            model_name='healthmonitoring',
            name='date_time',
            field=models.DateTimeField(null=True, verbose_name='Date/Time'),
        ),
        migrations.AddField(
            model_name='healthmonitoring',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.record'),
        ),
        migrations.AddField(
            model_name='housekeeping',
            name='date_time',
            field=models.DateTimeField(null=True, verbose_name='Date/Time'),
        ),
        migrations.AddField(
            model_name='housekeeping',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.record'),
        ),
        migrations.AddField(
            model_name='mobilityassistance',
            name='date_time',
            field=models.DateTimeField(null=True, verbose_name='Date/Time'),
        ),
        migrations.AddField(
            model_name='mobilityassistance',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.record'),
        ),
        migrations.AddField(
            model_name='nutritionhydration',
            name='date_time',
            field=models.DateTimeField(null=True, verbose_name='Date/Time'),
        ),
        migrations.AddField(
            model_name='nutritionhydration',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.record'),
        ),
        migrations.AddField(
            model_name='personalcare',
            name='date_time',
            field=models.DateTimeField(null=True, verbose_name='Date/Time'),
        ),
        migrations.AddField(
            model_name='personalcare',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.record'),
        ),
    ]
