# Generated by Django 5.0.6 on 2024-06-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_remove_personalcare_date_time_personalcare_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilityassistance',
            name='date_time',
        ),
        migrations.AddField(
            model_name='mobilityassistance',
            name='date',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='mobilityassistance',
            name='time',
            field=models.TimeField(null=True, verbose_name='Time'),
        ),
    ]
