# Generated by Django 5.0.6 on 2024-06-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_remove_activities_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='person_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
