# Generated by Django 5.0.6 on 2024-07-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0016_record_person_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='care_plan',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
